import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./CSS/Nav.css";
import "./CSS/Home.css";
import "./CSS/norefunds.css";
import "./CSS/Buttons/button2.css";
import "./CSS/Buttons/default.css";
import "./CSS/Buttons/button1.css";
import "./CSS/Buttons/google.css";
import "./CSS/Buttons/remove.css";
import "./CSS/Card.css";
import Navbar from "@/Components/NavBar";
import Footer from "@/Components/Footer";
import { GoogleOAuthProvider } from '@react-oauth/google';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AllSkillNoTalk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    
    <GoogleOAuthProvider clientId="84815521107-d8r0amo1a6ncidrml74gfhs19c3hh3uf.apps.googleusercontent.com">
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Navbar/>

        {children}

        <Footer/>
      </body>
    </html>
    </GoogleOAuthProvider>
    
 
    
  );
}
